"use client"

import { useState } from "react"
import Image from "next/image"
import Link from "next/link"
import { ResourceCard } from "@/components/resource-card"
import { Button } from "@/components/ui/button"
import { BookOpen, Headphones, Hammer, ChefHat, Cpu, Package, FileText, Book } from "lucide-react"

const categories = [
  { id: "all", name: "All Categories", icon: null },
  { id: "podcasts", name: "Podcasts", icon: Headphones },
  { id: "magazines", name: "Magazines", icon: FileText },
  { id: "kids-books", name: "Kids Books", icon: Book },
  { id: "parenting-books", name: "Parenting Books", icon: BookOpen },
  { id: "stem-activities", name: "STEM Activities", icon: Cpu },
  { id: "cooking-activities", name: "Cooking Activities", icon: ChefHat },
  { id: "diy-building", name: "DIY Building Activities", icon: Hammer },
  { id: "subscription-boxes", name: "Subscription Boxes", icon: Package },
]

const ageRanges = ["All Ages", "Ages 5-6", "Ages 7-8", "Ages 9-10"]

const resources = [
  {
    id: 1,
    title: "The Whole-Brain Child",
    description:
      "Revolutionary strategies to nurture your child's developing mind by Daniel J. Siegel and Tina Payne Bryson",
    image: "/book-cover-whole-brain-child.jpg",
    category: "parenting-books",
    type: "Book",
    ageRange: "Ages 5-10",
    link: "https://www.amazon.com/Whole-Brain-Child-Revolutionary-Strategies-Developing/dp/0553386697",
  },
  {
    id: 2,
    title: "How to Talk So Kids Will Listen",
    description: "Time-tested communication strategies that strengthen parent-child relationships by Adele Faber",
    image: "/book-cover-how-to-talk.jpg",
    category: "parenting-books",
    type: "Book",
    ageRange: "Ages 5-10",
    link: "https://www.amazon.com/How-Talk-Kids-Will-Listen/dp/1451663889",
  },
  {
    id: 3,
    title: "Positive Discipline",
    description: "Effective strategies for raising responsible, respectful children by Jane Nelsen",
    image: "/book-cover-positive-discipline.jpg",
    category: "parenting-books",
    type: "Book",
    ageRange: "Ages 5-10",
    link: "https://www.amazon.com/Positive-Discipline-Jane-Nelsen-Ed-D/dp/0345487672",
  },
  {
    id: 4,
    title: "The 5 Love Languages of Children",
    description: "Discover your child's primary love language and strengthen your connection by Gary Chapman",
    image: "/book-cover-5-love-languages.jpg",
    category: "parenting-books",
    type: "Book",
    ageRange: "Ages 5-10",
    link: "https://www.amazon.com/Love-Languages-Children-Secret-Effectively/dp/0802412858",
  },
  {
    id: 30,
    title: "Simplicity Parenting",
    description: "Using the power of less to raise calmer, happier children by Kim John Payne",
    image: "/book-cover-simplicity-parenting.jpg",
    category: "parenting-books",
    type: "Book",
    ageRange: "Ages 5-10",
    link: "https://www.amazon.com/Simplicity-Parenting-Extraordinary-Calmer-Happier/dp/0375869026",
  },
  {
    id: 31,
    title: "Where the Wild Things Are",
    description: "Classic picture book about imagination and adventure by Maurice Sendak",
    image: "/book-cover-wild-things.jpg",
    category: "kids-books",
    type: "Book",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/Where-Wild-Things-Maurice-Sendak/dp/0060254920",
  },
  {
    id: 32,
    title: "The Very Hungry Caterpillar",
    description: "Beloved children's book about growth and transformation by Eric Carle",
    image: "/book-cover-hungry-caterpillar.jpg",
    category: "kids-books",
    type: "Book",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/Very-Hungry-Caterpillar-Eric-Carle/dp/0399226907",
  },
  {
    id: 33,
    title: "Charlotte's Web",
    description: "Timeless story of friendship and loyalty by E.B. White",
    image: "/book-cover-charlottes-web.jpg",
    category: "kids-books",
    type: "Book",
    ageRange: "Ages 7-8",
    link: "https://www.amazon.com/Charlottes-Web-E-B-White/dp/0064400557",
  },
  {
    id: 34,
    title: "Wonder",
    description: "Inspiring story about kindness and acceptance by R.J. Palacio",
    image: "/book-cover-wonder.jpg",
    category: "kids-books",
    type: "Book",
    ageRange: "Ages 9-10",
    link: "https://www.amazon.com/Wonder-R-J-Palacio/dp/0375869026",
  },
  {
    id: 35,
    title: "Harry Potter and the Sorcerer's Stone",
    description: "Magical adventure series that captivates young readers by J.K. Rowling",
    image: "/book-cover-harry-potter.jpg",
    category: "kids-books",
    type: "Book",
    ageRange: "Ages 9-10",
    link: "https://www.amazon.com/Harry-Potter-Sorcerers-Stone-Rowling/dp/0590353403",
  },
  {
    id: 5,
    title: "Good Inside with Dr. Becky",
    description: "Dr. Becky Kennedy shares practical parenting strategies and insights",
    image: "/podcast-artwork-good-inside.jpg",
    category: "podcasts",
    type: "Podcast",
    ageRange: "All Ages",
    link: "https://www.goodinside.com/podcast/",
  },
  {
    id: 36,
    title: "The Longest Shortest Time",
    description: "Honest conversations about the beautiful, messy reality of parenting",
    image: "/podcast-artwork-longest-shortest-time.jpg",
    category: "podcasts",
    type: "Podcast",
    ageRange: "All Ages",
    link: "https://longestshortesttime.com/",
  },
  {
    id: 37,
    title: "Unruffled",
    description: "Janet Lansbury's respectful parenting advice and guidance",
    image: "/podcast-artwork-unruffled.jpg",
    category: "podcasts",
    type: "Podcast",
    ageRange: "All Ages",
    link: "https://www.janetlansbury.com/podcast-audio/",
  },
  {
    id: 38,
    title: "The Mom Hour",
    description: "Real talk about motherhood, parenting, and life balance",
    image: "/podcast-artwork-mom-hour.jpg",
    category: "podcasts",
    type: "Podcast",
    ageRange: "All Ages",
    link: "https://themomhour.com/",
  },
  {
    id: 39,
    title: "Karma & Chaos",
    description: "Kail Lowry & Becky Hayter discuss real parenting challenges with humor and honesty",
    image: "/karma-and-chaos-podcast-cover-art-colorful-microph.jpg",
    category: "podcasts",
    type: "Podcast",
    ageRange: "All Ages",
    link: "https://podcasts.apple.com/us/podcast/karma-chaos-with-kail-lowry-becky-hayter/id1532102239",
  },
  {
    id: 40,
    title: "For Crying Out Loud",
    description: "Hilarious and heartfelt conversations about the ups and downs of parenting",
    image: "/for-crying-out-loud-podcast-cover-art-baby-crying.jpg",
    category: "podcasts",
    type: "Podcast",
    ageRange: "All Ages",
    link: "https://podcasts.apple.com/us/podcast/for-crying-out-loud/id354082588",
  },
  {
    id: 41,
    title: "Care and Feeding",
    description: "Slate's parenting show offering advice on raising kids in today's world",
    image: "/care-and-feeding-slate-podcast-cover-art-parenting.jpg",
    category: "podcasts",
    type: "Podcast",
    ageRange: "All Ages",
    link: "https://podcasts.apple.com/us/podcast/care-and-feeding-slates-parenting-show/id774383607",
  },
  {
    id: 42,
    title: "The PedsDocTalk Podcast",
    description: "Child health, development, and parenting advice from a pediatrician mom",
    image: "/pedsdoctalk-podcast.webp",
    category: "podcasts",
    type: "Podcast",
    ageRange: "All Ages",
    link: "https://podcasts.apple.com/us/podcast/the-pedsdoctalk-podcast/id1501057527",
  },
  {
    id: 43,
    title: "Parenting Hell",
    description: "Rob Beckett and Josh Widdicombe share hilarious parenting stories and struggles",
    image: "/parenting-hell-podcast-cover-art-comedy-microphone.jpg",
    category: "podcasts",
    type: "Podcast",
    ageRange: "All Ages",
    link: "https://podcasts.apple.com/us/podcast/parenting-hell-with-rob-beckett-and-josh-widdicombe/id1510251497",
  },
  {
    id: 44,
    title: "Motherhood in Black and White",
    description: "Exploring parenting through diverse perspectives and experiences",
    image: "/motherhood-in-black-and-white.webp",
    category: "podcasts",
    type: "Podcast",
    ageRange: "All Ages",
    link: "https://podcasts.apple.com/gb/podcast/motherhood-in-black-white/id1525043882",
  },
  {
    id: 45,
    title: "Wow in the World",
    description: "Science and curiosity podcast that makes learning fun for kids",
    image: "/wow-in-the-world-kids-podcast-cover-art-science-co.jpg",
    category: "podcasts",
    type: "Podcast",
    ageRange: "Ages 5-10",
    link: "https://podcasts.apple.com/us/podcast/wow-in-the-world/id1233834541",
  },
  {
    id: 46,
    title: "Story Pirates",
    description: "Professional actors bring kids' stories to life with music and comedy",
    image: "/story-pirates-podcast-cover-art-pirate-ship-kids-s.jpg",
    category: "podcasts",
    type: "Podcast",
    ageRange: "Ages 5-10",
    link: "https://open.spotify.com/show/0OHMYcZChEVgTx2jz0yzze",
  },
  {
    id: 47,
    title: "Circle Round",
    description: "Folktales from around the world adapted for modern kids",
    image: "/circle-round-podcast-cover-art-folktales-storytell.jpg",
    category: "podcasts",
    type: "Podcast",
    ageRange: "Ages 5-10",
    link: "https://podcasts.apple.com/us/podcast/circle-round/id1246443751",
  },
  {
    id: 48,
    title: "Brains On!",
    description: "Science podcast for curious kids exploring how the world works",
    image: "/brains-on-science-podcast-cover-art-brain-kids-lea.jpg",
    category: "podcasts",
    type: "Podcast",
    ageRange: "Ages 7-10",
    link: "https://open.spotify.com/show/4EaTaVeNXR4QSFAArpyZyd",
  },
  {
    id: 100,
    title: "National Geographic Ultimate Volcano Kit",
    description: "Erupting volcano science kit with real lava eruptions and learning guide",
    image: "/national-geographic-volcano-science-kit-box-with-e.jpg",
    category: "stem-activities",
    type: "Activity",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/NATIONAL-GEOGRAPHIC-Ultimate-Volcano-Kit/dp/B08KTWWF1Y",
  },
  {
    id: 101,
    title: "National Geographic Mega Crystal Growing Kit",
    description: "Grow 6 vibrant crystals with light-up display stand for hands-on science learning",
    image: "/national-geographic-crystal-growing-kit-with-color.jpg",
    category: "stem-activities",
    type: "Activity",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/NATIONAL-GEOGRAPHIC-Mega-Crystal-Growing/dp/B084R8X13B",
  },
  {
    id: 102,
    title: "Thames & Kosmos Ooze Labs Chemistry Station",
    description: "20 non-hazardous experiments including safe slime, acids, bases and chromatography",
    image: "/thames-kosmos-ooze-labs-chemistry-station-science-.jpg",
    category: "stem-activities",
    type: "Activity",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/Thames-Kosmos-Chemistry-Station-Experiment/dp/B07B7W5S3H",
  },
  {
    id: 103,
    title: "4M Weather Science Kit",
    description: "Create rain, clouds, and weather phenomena to understand meteorology",
    image: "/4m-weather-science-kit-with-weather-station-tools-.jpg",
    category: "stem-activities",
    type: "Activity",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/4M-3689-Weather-Science-Kit/dp/B00BFPH2LY",
  },
  {
    id: 104,
    title: "National Geographic Mega Slime Kit & Putty Lab",
    description: "Make 4 types of slime and 4 types of putty including magnetic putty",
    image: "/national-geographic-slime-kit-with-colorful-slime-.jpg",
    category: "stem-activities",
    type: "Activity",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/NATIONAL-GEOGRAPHIC-Slime-Putty-Glow/dp/B07B4MTWTX",
  },
  {
    id: 105,
    title: "360° Orbiting Solar System Model Kit",
    description: "Paint and build a working solar system model with 8 planets that orbit",
    image: "/solar-system-model-kit-with-planets-and-orbiting-m.jpg",
    category: "stem-activities",
    type: "Activity",
    ageRange: "Ages 7-8",
    link: "https://www.amazon.com/dp/B0BXQZ8VYJ",
  },
  {
    id: 106,
    title: "National Geographic Jumbo Crystal Growing Kit",
    description: "Grow a giant glow-in-the-dark crystal in just a few days",
    image: "/national-geographic-jumbo-crystal-growing-kit-with.jpg",
    category: "stem-activities",
    type: "Activity",
    ageRange: "Ages 7-8",
    link: "https://www.amazon.com/National-Geographic-Jumbo-Crystal-Growing/dp/B0CZPLQT11",
  },
  {
    id: 107,
    title: "Thames & Kosmos Easy Electric Circuits Kit",
    description: "15 experiments and 5 motorized models to learn about electricity and circuits",
    image: "/thames-kosmos-electric-circuits-kit-with-wires-mot.jpg",
    category: "stem-activities",
    type: "Activity",
    ageRange: "Ages 7-8",
    link: "https://www.amazon.com/Thames-Kosmos-Essential-Circuitry-Experiments/dp/B08TVYM5RS",
  },
  {
    id: 108,
    title: "Kids Beginner Microscope Kit",
    description: "100X-1200X magnification microscope with LED light and prepared slides",
    image: "/kids-microscope-kit-with-led-light-prepared-slides.jpg",
    category: "stem-activities",
    type: "Activity",
    ageRange: "Ages 7-8",
    link: "https://www.amazon.com/58-Piece-Kids-Microscope-Kit-Magnification/dp/B09DVFG6JN",
  },
  {
    id: 109,
    title: "National Geographic Stunning Chemistry Set",
    description: "Over 100 experiments including volcano eruption and rocket launch",
    image: "/national-geographic-chemistry-set-with-test-tubes-.jpg",
    category: "stem-activities",
    type: "Activity",
    ageRange: "Ages 7-8",
    link: "https://www.amazon.com/NATIONAL-GEOGRAPHIC-Stunning-Chemistry-Set/dp/B0BXQYQZ8V",
  },
  {
    id: 110,
    title: "SMARTLAB Toys Storm Watcher Weather Lab",
    description: "18 wild weather experiments to create storms, tornadoes, and lightning",
    image: "/smartlab-storm-watcher-weather-lab-kit-with-weathe.jpg",
    category: "stem-activities",
    type: "Activity",
    ageRange: "Ages 9-10",
    link: "https://www.amazon.com/SmartLab-Toys-Storm-Watcher-Weather/dp/B08BVYJ76L",
  },
  {
    id: 111,
    title: "Discovery Extreme Weather STEM Science Kit",
    description: "Create artificial snow, erupting volcanoes, and extreme weather phenomena",
    image: "/discovery-extreme-weather-science-kit-with-weather.jpg",
    category: "stem-activities",
    type: "Activity",
    ageRange: "Ages 9-10",
    link: "https://www.amazon.com/Discovery-Kids-Experiments-Erupting-Artificial/dp/B01N7WJSJL",
  },
  {
    id: 112,
    title: "BATURU STEM Electronics Kit",
    description: "70 science experiments teaching electronics and circuit building",
    image: "/baturu-stem-electronics-kit-with-circuit-boards-an.jpg",
    category: "stem-activities",
    type: "Activity",
    ageRange: "Ages 9-10",
    link: "https://www.amazon.com/BATURU-Circuits-40-Electronics-Exploration/dp/B0CWLDSRCD",
  },
  {
    id: 113,
    title: "Explore Science 50 Electronic Circuits Kit",
    description: "Build 50 different electronic circuits with snap-together components",
    image: "/explore-science-electronic-circuits-kit-with-snap-.jpg",
    category: "stem-activities",
    type: "Activity",
    ageRange: "Ages 9-10",
    link: "https://www.amazon.com/Explore-Science-Electronic-Experiment-Set/dp/B09D8M71LW",
  },
  {
    id: 114,
    title: "National Geographic Mega Science Lab",
    description: "Over 130 experiments featuring earth science, chemistry, and magic STEM projects",
    image: "/national-geographic-mega-science-lab-kit-with-mult.jpg",
    category: "stem-activities",
    type: "Activity",
    ageRange: "Ages 9-10",
    link: "https://www.amazon.com/NATIONAL-GEOGRAPHIC-Mega-Science-Lab/dp/B09LRHSXW9",
  },
  {
    id: 200,
    title: "LEGO Classic Large Creative Brick Box",
    description: "790-piece building set with 33 different colors for endless creative construction",
    image: "/lego-classic-large-creative-brick-box-with-colorfu.jpg",
    category: "diy-building",
    type: "Product",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/LEGO-Classic-Creative-Building-Pieces/dp/B00NHQFA3I",
  },
  {
    id: 201,
    title: "Plus-Plus Open Play Set",
    description: "240-piece interlocking building blocks in basic colors for creative construction",
    image: "/plus-plus-colorful-interlocking-building-blocks-in.jpg",
    category: "diy-building",
    type: "Product",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/PLUS-Plus-Plus-Construction-Building-Interlocking/dp/B00JZO7CNA",
  },
  {
    id: 202,
    title: "Melissa & Doug Wooden Building Blocks Set",
    description: "100-piece wooden blocks in 4 colors and 9 shapes for classic construction play",
    image: "/wooden-building-blocks-set-with-natural-wood-and-c.jpg",
    category: "diy-building",
    type: "Product",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/Melissa-Doug-Wooden-Building-Blocks/dp/B00005RF5G",
  },
  {
    id: 203,
    title: "Lincoln Logs Classic Meetinghouse",
    description: "111-piece real wood building set to create classic log cabin structures",
    image: "/lincoln-logs-wooden-building-set-with-log-cabin-pi.jpg",
    category: "diy-building",
    type: "Product",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/Lincoln-Logs-Classic-Meetinghouse-Building/dp/B00NHQFCNC",
  },
  {
    id: 204,
    title: "Tinkertoy 30 Model Super Building Set",
    description: "200-piece classic construction set to build 30 different models",
    image: "/tinkertoy-building-set-with-colorful-rods-and-conn.jpg",
    category: "diy-building",
    type: "Product",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/TINKERTOY-Model-Super-Building-Set/dp/B00JRGVEG2",
  },
  {
    id: 205,
    title: "Marble Run Building Blocks",
    description: "135-piece marble maze construction set with tracks and marbles for STEM learning",
    image: "/colorful-marble-run-building-blocks-with-transpare.jpg",
    category: "diy-building",
    type: "Product",
    ageRange: "Ages 7-8",
    link: "https://www.amazon.com/Marble-Run-Set-135PCS-Marble-Maze-Construction-Building-Block-Kid-Toys-Marble-Track-STEM-Toys-Learning-Education-10-11-12-Years-Old-Boys/dp/B09BTJVS31",
  },
  {
    id: 206,
    title: "Geomag Classic Magnetic Building Set",
    description: "60-piece magnetic construction toy with rods and steel spheres for 3D structures",
    image: "/geomag-magnetic-building-set-with-colorful-rods-an.jpg",
    category: "diy-building",
    type: "Product",
    ageRange: "Ages 7-8",
    link: "https://www.amazon.com/Geomag-Classic-Color-Piece-Magnetic/dp/B00HNMWFXE",
  },
  {
    id: 207,
    title: "K'NEX Thrill Rides Building Set",
    description: "Building set with 473 pieces to create working roller coaster models",
    image: "/k-nex-roller-coaster-building-set-with-colorful-pi.jpg",
    category: "diy-building",
    type: "Product",
    ageRange: "Ages 7-8",
    link: "https://www.amazon.com/KNEX-Thrill-Rides-Roller-Coaster/dp/B00TXYKP5E",
  },
  {
    id: 208,
    title: "Wondertoys Wooden Logs Building Set",
    description: "530-piece wooden log construction set for building cabins and structures",
    image: "/wooden-logs-building-set-with-natural-wood-pieces-.jpg",
    category: "diy-building",
    type: "Product",
    ageRange: "Ages 7-8",
    link: "https://www.amazon.com/Wondertoys-Building-Construction-Engineering-Educational/dp/B0BVR1NDKW",
  },
  {
    id: 209,
    title: "Magna-Tiles Clear Colors 100 Piece Set",
    description: "Magnetic building tiles in translucent colors for creative 3D construction",
    image: "/magna-tiles-clear-colorful-magnetic-building-tiles.jpg",
    category: "diy-building",
    type: "Product",
    ageRange: "Ages 7-8",
    link: "https://www.amazon.com/Magna-Tiles-Clear-Colors-100-Piece/dp/B000CBSNRY",
  },
  {
    id: 210,
    title: "HOGOKIDS 5 in 1 STEM Building Set",
    description: "APP and remote-controlled building kit with LED lights for cars, robots, and tanks",
    image: "/hogokids-stem-building-set-with-led-lights-and-rem.jpg",
    category: "diy-building",
    type: "Product",
    ageRange: "Ages 9-10",
    link: "https://www.amazon.com/HOGOKIDS-STEM-Building-Set-Light/dp/B0C9Q61RJ2",
  },
  {
    id: 211,
    title: "Butterfly Edufields 10in1 STEM Robotics Kit",
    description: "Engineering building kit to create 10 different robotic models",
    image: "/stem-robotics-building-kit-with-mechanical-parts-a.jpg",
    category: "diy-building",
    type: "Product",
    ageRange: "Ages 9-10",
    link: "https://www.amazon.com/Butterfly-EduFields-Educational-Building-Robotics/dp/B07VQKV6TD",
  },
  {
    id: 212,
    title: "SainSmart Jr. Wooden Log Cabin Set",
    description: "450-piece classic STEM construction kit with colorful wood logs for building houses",
    image: "/wooden-log-cabin-building-set-with-colorful-logs-a.jpg",
    category: "diy-building",
    type: "Product",
    ageRange: "Ages 9-10",
    link: "https://www.amazon.com/SainSmart-Jr-Building-Construction-Engineering-20-338/dp/B0BDKPNMG7",
  },
  {
    id: 213,
    title: "Geomag Mechanics Magnetic Motion",
    description: "146-piece magnetic building set with gears and mechanical elements for moving structures",
    image: "/geomag-mechanics-magnetic-building-set-with-gears-.jpg",
    category: "diy-building",
    type: "Product",
    ageRange: "Ages 9-10",
    link: "https://www.amazon.com/Geomag-Mechanics-Magnetic-Educational-Construction/dp/B07PM7SZHV",
  },
  // {
  //   id: 214,
  //   title: "Tinkertoy Retro Building Set Tin",
  //   description: "100-part classic wooden construction set in collectible tin container",
  //   image: "/placeholder.svg?height=400&width=300",
  //   category: "diy-building",
  //   type: "Product",
  //   ageRange: "Ages 9-10",
  //   link: "https://www.amazon.com/KNEX-TINKERTOY-Retro-Building-Collectible/dp/B06XKJPQVR",
  // },
  {
    id: 300,
    title: "Tovla Jr. Kid Safe Knife Set",
    description: "3-piece safe cooking knife set for kids ages 4-12, BPA-free and dishwasher-safe",
    image: "/colorful-kid-safe-cooking-knife-set-with-three-siz.jpg",
    category: "cooking-activities",
    type: "Product",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/dp/B0BXMJHFXP",
  },
  {
    id: 301,
    title: "Baketivity Kids Baking Tools Set",
    description: "31-piece real baking utensils set with recipe cards for young chefs",
    image: "/kids-baking-tools-set-with-colorful-utensils-and-r.jpg",
    category: "cooking-activities",
    type: "Product",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/dp/B08MQRTRYS",
  },
  {
    id: 302,
    title: "WeeSprout Little Chef Cooking Set",
    description: "14-piece kids cooking and baking set with real kitchen tools and apron",
    image: "/kids-chef-cooking-set-with-apron-and-colorful-uten.jpg",
    category: "cooking-activities",
    type: "Product",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/dp/B0B5HW645J",
  },
  {
    id: 303,
    title: "Kids Cookie Decorating Kit",
    description: "Professional cookie decorating kit with tools and accessories",
    image: "/kids-cookie-decorating-kit-with-icing-tools-and-sp.jpg",
    category: "cooking-activities",
    type: "Product",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/dp/B0BXMJHFXP",
  },
  {
    id: 304,
    title: "Little Cook Measuring Cups Set",
    description: "12-piece colorful measuring cups and spoons for baking and cooking",
    image: "/colorful-stackable-measuring-cups-and-spoons-for-k.jpg",
    category: "cooking-activities",
    type: "Product",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/dp/B0BY92B5B3",
  },
  {
    id: 305,
    title: "MasterChef Junior Pizza Cooking Set",
    description: "5-piece pizza making kit with real cookware, recipes, board, and roller",
    image: "/kids-pizza-making-set-with-rolling-pin-and-pizza-p.jpg",
    category: "cooking-activities",
    type: "Product",
    ageRange: "Ages 7-8",
    link: "https://www.amazon.com/dp/B000WDT934",
  },
  {
    id: 306,
    title: "Baketivity DIY Cake Pop Baking Kit",
    description: "Complete cake pop making kit with all ingredients and tools included",
    image: "/kids-cake-pop-baking-kit-with-molds-and-decorating.jpg",
    category: "cooking-activities",
    type: "Product",
    ageRange: "Ages 7-8",
    link: "https://www.amazon.com/dp/B08MQRTRYS",
  },
  {
    id: 307,
    title: "Opinel Le Petit Chef Kitchen Set",
    description: "3-piece French chef set with rounded tip knife, finger guard, and peeler",
    image: "/french-kids-chef-knife-set-with-finger-guard-and-p.jpg",
    category: "cooking-activities",
    type: "Product",
    ageRange: "Ages 7-8",
    link: "https://www.amazon.com/dp/B01N7T6R6T",
  },
  {
    id: 308,
    title: "Montessori Kids Knife Set",
    description: "13-piece wooden kids kitchen knife set for real cooking",
    image: "/wooden-montessori-kids-knife-set-with-cutting-boar.jpg",
    category: "cooking-activities",
    type: "Product",
    ageRange: "Ages 7-8",
    link: "https://www.amazon.com/dp/B0C1QXQXQX",
  },
  {
    id: 309,
    title: "IELEK Real Baking Set with Apron",
    description: "Complete pastry cooking kit with apron, rolling pin, and recipes",
    image: "/kids-baking-set-with-chef-apron-and-rolling-pin.jpg",
    category: "cooking-activities",
    type: "Product",
    ageRange: "Ages 7-8",
    link: "https://www.amazon.com/dp/B08HX354D5",
  },
  {
    id: 310,
    title: "GIFTINBOX Kids Cooking Set",
    description: "54-piece complete cooking and baking kit with utensils and accessories",
    image: "/large-kids-cooking-set-with-many-colorful-utensils.jpg",
    category: "cooking-activities",
    type: "Product",
    ageRange: "Ages 9-10",
    link: "https://www.amazon.com/dp/B09MRGWR6N",
  },
  {
    id: 311,
    title: "Kizzikids Safe Knife Set",
    description: "4-piece round tip serrated edge knives with firm grip, BPA-free",
    image: "/colorful-kids-safe-knives-with-round-tips-and-serr.jpg",
    category: "cooking-activities",
    type: "Product",
    ageRange: "Ages 9-10",
    link: "https://www.amazon.com/dp/B0BXMJHFXP",
  },
  {
    id: 312,
    title: "Tovla Jr. Ultimate Pizza Kit",
    description: "Complete pizza making kit for kids with all tools and accessories",
    image: "/kids-ultimate-pizza-making-kit-with-tools-and-acce.jpg",
    category: "cooking-activities",
    type: "Product",
    ageRange: "Ages 9-10",
    link: "https://www.amazon.com/dp/B0CZBXWY33",
  },
  {
    id: 313,
    title: "Baketivity Kids Cooking Utensils",
    description: "Real cooking utensils set with kitchen tool guide for young chefs",
    image: "/kids-cooking-utensils-set-with-spatulas-and-mixing.jpg",
    category: "cooking-activities",
    type: "Product",
    ageRange: "Ages 9-10",
    link: "https://www.amazon.com/dp/B0B9FQ5BNJ",
  },
  {
    id: 314,
    title: "WeeSprout Ultimate Baking Kit",
    description: "Complete baking kit with child-sized utensils and measuring tools",
    image: "/kids-ultimate-baking-kit-with-child-sized-measurin.jpg",
    category: "cooking-activities",
    type: "Product",
    ageRange: "Ages 9-10",
    link: "https://www.amazon.com/dp/B0C8R4BZ1V",
  },
  {
    id: 400,
    title: "LEGO Challenges",
    description: "Build creative structures with LEGO building challenges",
    image: "/activity-lego-challenges.jpg",
    category: "stem-activities",
    type: "Activity",
    ageRange: "Ages 5-6",
    link: "https://www.steamsational.com/30-lego-building-challenges-for-kids/",
  },
  {
    id: 401,
    title: "Pattern Blocks",
    description: "Create geometric patterns and designs with colorful blocks",
    image: "/activity-pattern-blocks.jpg",
    category: "stem-activities",
    type: "Activity",
    ageRange: "Ages 5-6",
    link: "https://www.mathlearningcenter.org/apps/pattern-shapes",
  },
  {
    id: 402,
    title: "Counting Games",
    description: "Fun math games to practice counting and number recognition",
    image: "/activity-counting-games.jpg",
    category: "stem-activities",
    type: "Activity",
    ageRange: "Ages 5-6",
    link: "https://www.mathgames.com/skill/k.1-counting",
  },
  {
    id: 403,
    title: "Block Tower Building",
    description: "Engineer tall towers and test structural stability",
    image: "/activity-block-towers.jpg",
    category: "stem-activities",
    type: "Activity",
    ageRange: "Ages 5-6",
    link: "https://www.steamsational.com/block-tower-building-challenge/",
  },
  {
    id: 404,
    title: "Magnet Exploration",
    description: "Discover magnetic properties through hands-on experiments",
    image: "/activity-magnets.jpg",
    category: "stem-activities",
    type: "Activity",
    ageRange: "Ages 5-6",
    link: "https://www.steamsational.com/magnet-activities-for-kids/",
  },
  {
    id: 405,
    title: "Bridge Building",
    description: "Design and construct bridges that can hold weight",
    image: "/activity-bridge-building.jpg",
    category: "stem-activities",
    type: "Activity",
    ageRange: "Ages 7-8",
    link: "https://www.sciencebuddies.org/stem-activities/bridge-building",
  },
  {
    id: 406,
    title: "Robot Building",
    description: "Assemble simple robots with motors and basic circuits",
    image: "/activity-robot-building.jpg",
    category: "stem-activities",
    type: "Activity",
    ageRange: "Ages 7-8",
    link: "https://www.instructables.com/Simple-Bristlebot-Robot/",
  },
  {
    id: 407,
    title: "Simple Coding",
    description: "Learn basic coding concepts with visual programming",
    image: "/activity-simple-coding.jpg",
    category: "stem-activities",
    type: "Activity",
    ageRange: "Ages 7-8",
    link: "https://code.org/learn",
  },
  {
    id: 408,
    title: "Math Scavenger Hunts",
    description: "Find and solve math problems hidden around the house",
    image: "/activity-math-scavenger.jpg",
    category: "stem-activities",
    type: "Activity",
    ageRange: "Ages 7-8",
    link: "https://www.steamsational.com/math-scavenger-hunt-for-kids/",
  },
  {
    id: 409,
    title: "Parachute Design",
    description: "Engineer parachutes and test air resistance principles",
    image: "/activity-parachute.jpg",
    category: "stem-activities",
    type: "Activity",
    ageRange: "Ages 7-8",
    link: "https://www.sciencebuddies.org/stem-activities/parachute",
  },
  {
    id: 410,
    title: "Robot Programming",
    description: "Program robots to complete tasks and navigate obstacles",
    image: "/activity-robot-programming.jpg",
    category: "stem-activities",
    type: "Activity",
    ageRange: "Ages 9-10",
    link: "https://www.lego.com/en-us/themes/mindstorms",
  },
  {
    id: 411,
    title: "Roller Coaster Design",
    description: "Build working roller coasters and learn about physics",
    image: "/activity-roller-coaster.jpg",
    category: "stem-activities",
    type: "Activity",
    ageRange: "Ages 9-10",
    link: "https://www.sciencebuddies.org/stem-activities/roller-coaster",
  },
  {
    id: 412,
    title: "Skyscraper Engineering",
    description: "Design and build tall structures that withstand forces",
    image: "/activity-skyscraper.jpg",
    category: "stem-activities",
    type: "Activity",
    ageRange: "Ages 9-10",
    link: "https://www.sciencebuddies.org/stem-activities/earthquake-resistant-building",
  },
  {
    id: 413,
    title: "Circuit Boards",
    description: "Build electronic circuits with LEDs, batteries, and switches",
    image: "/activity-circuit-boards.jpg",
    category: "stem-activities",
    type: "Activity",
    ageRange: "Ages 9-10",
    link: "https://www.sciencebuddies.org/stem-activities/simple-circuit",
  },
  {
    id: 414,
    title: "Math Games",
    description: "Challenging math puzzles and strategy games",
    image: "/activity-math-games.jpg",
    category: "stem-activities",
    type: "Activity",
    ageRange: "Ages 9-10",
    link: "https://www.mathplayground.com/",
  },
  {
    id: 600,
    title: "Snap Circuits SC-300 Electronics Kit",
    description: "Build over 300 working electronic circuits and learn about electricity with snap-together components",
    image: "/snap-circuits-sc-300-electronics-kit-box-with-colo.jpg",
    category: "stem-activities",
    type: "Product",
    ageRange: "Ages 7-8",
    link: "https://www.amazon.com/Snap-Circuits-SC-300-Electronics-Exploration/dp/B0000683A4",
  },
  {
    id: 601,
    title: "National Geographic Mega Science Lab",
    description: "Over 130 hands-on experiments covering chemistry, earth science, and magic STEM projects",
    image: "/national-geographic-mega-science-lab-kit-box-with-.jpg",
    category: "stem-activities",
    type: "Product",
    ageRange: "Ages 9-10",
    link: "https://www.amazon.com/National-Geographic-Mega-Science-Lab/dp/B07VQKV6TD",
  },
  {
    id: 602,
    title: "Magna-Tiles Clear Colors 100 Piece Set",
    description: "America's #1 magnetic building tiles for creative construction and spatial reasoning",
    image: "/magna-tiles-clear-colorful-magnetic-building-tiles.jpg",
    category: "stem-activities",
    type: "Product",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/Magna-Tiles-100-Piece-Clear-Colors-Award-Winning/dp/B000CBSNRY",
  },
  {
    id: 603,
    title: "Osmo Coding Starter Kit for iPad",
    description: "Interactive coding games that teach programming fundamentals through hands-on play",
    image: "/osmo-coding-starter-kit-with-ipad-base-and-colorfu.jpg",
    category: "stem-activities",
    type: "Product",
    ageRange: "Ages 7-8",
    link: "https://www.amazon.com/Osmo-Educational-Games-Ages-Puzzles-STEM-Fundamentals/dp/B085NN5678",
  },
  {
    id: 604,
    title: "ThinkFun Gravity Maze",
    description: "Award-winning marble run logic game that builds spatial reasoning and planning skills",
    image: "/thinkfun-gravity-maze-marble-run-logic-game-with-c.jpg",
    category: "stem-activities",
    type: "Product",
    ageRange: "Ages 7-8",
    link: "https://www.amazon.com/ThinkFun-Gravity-Marble-Logic-Girls/dp/B00IUAAK2A",
  },
  {
    id: 605,
    title: "Botley 2.0 Coding Robot",
    description: "Screen-free coding robot that teaches programming through hands-on activities",
    image: "/botley-2-0-blue-coding-robot-with-remote-control-a.jpg",
    category: "stem-activities",
    type: "Product",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/Learning-Resources-Botley-Coding-Robot/dp/B083T5G5ZK",
  },
  {
    id: 606,
    title: "K'NEX Thrill Rides Building Set",
    description: "Engineering construction set with motorized parts to build working roller coasters",
    image: "/k-nex-thrill-rides-roller-coaster-building-set-wit.jpg",
    category: "stem-activities",
    type: "Product",
    ageRange: "Ages 9-10",
    link: "https://www.amazon.com/KNEX-Thrill-Rides-Bionic-Building/dp/B00TXYKP5Y",
  },
  {
    id: 607,
    title: "Sphero Mini Coding Robot Ball",
    description: "App-enabled robot ball that teaches coding through games and creative activities",
    image: "/sphero-mini-blue-robot-ball-with-app-interface.jpg",
    category: "stem-activities",
    type: "Product",
    ageRange: "Ages 7-8",
    link: "https://www.amazon.com/Sphero-M001BRW-Mini-App-Enabled-Robot/dp/B072B6QVVW",
  },
  {
    id: 608,
    title: "LEGO Classic Creative Building Set",
    description: "1,500 pieces for endless creative building and engineering exploration",
    image: "/lego-classic-creative-building-bricks-set-with-col.jpg",
    category: "stem-activities",
    type: "Product",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/LEGO-Classic-Creative-Building-Bricks/dp/B07GY8KZRZ",
  },
  {
    id: 609,
    title: "Thames & Kosmos RoboRails",
    description: "Build a robot monorail system and explore physics and gyroscopic forces",
    image: "/thames-.jpg",
    category: "stem-activities",
    type: "Product",
    ageRange: "Ages 9-10",
    link: "https://www.amazon.com/Thames-Kosmos-RoboRails-STEM-Kit/dp/B0CRJW2GT8",
  },
  {
    id: 610,
    title: "GeoSafari Jr. Talking Microscope",
    description: "Kid-friendly microscope with voice narration featuring 60 images and 100+ facts",
    image: "/geosafari-jr-talking-microscope-for-kids-with-colo.jpg",
    category: "stem-activities",
    type: "Product",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/Educational-Insights-GeoSafari-Talking-Microscope/dp/B01MXZB4YO",
  },
  {
    id: 611,
    title: "Makeblock mBot Robot Kit",
    description: "Programmable robot kit for learning coding, electronics, and robotics",
    image: "/makeblock-mbot-programmable-robot-kit-with-blue-ch.jpg",
    category: "stem-activities",
    type: "Product",
    ageRange: "Ages 9-10",
    link: "https://www.amazon.com/Makeblock-mBot-Robot-Kit-Kids/dp/B00SK5RUQY",
  },
  {
    id: 612,
    title: "4M Tin Can Robot",
    description: "Build a walking robot from a recycled tin can and learn about motors and mechanics",
    image: "/4m-tin-can-robot-kit-with-recycled-can-and-motor-p.jpg",
    category: "stem-activities",
    type: "Product",
    ageRange: "Ages 7-8",
    link: "https://www.amazon.com/4M-Tin-Can-Robot/dp/B000BKQG8Y",
  },
  {
    id: 613,
    title: "Learning Resources Gears! Gears! Gears!",
    description: "Colorful interlocking gears for building and learning about simple machines",
    image: "/learning-resources-gears-building-set-with-colorfu.jpg",
    category: "stem-activities",
    type: "Product",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/Learning-Resources-Gears-Beginners-Building/dp/B000066PL0",
  },
  {
    id: 614,
    title: "4M Kitchen Science Kit",
    description: "Turn your kitchen into a science lab with fun food experiments",
    image: "/4m-kitchen-science-kit-box-with-food-experiments.jpg",
    category: "stem-activities",
    type: "Product",
    ageRange: "Ages 7-8",
    link: "https://www.amazon.com/4M-Kitchen-Science-Kit-FSG3296/dp/B002ACVV7I",
  },
  // {
  //   id: 615,
  //   title: "Scientific Explorer Mind Blowing Science Kit",
  //   description: "Perform amazing science experiments with easy-to-follow instructions",
  //   image: "/placeholder.svg?height=400&width=300",
  //   category: "stem-activities",
  //   type: "Product",
  //   ageRange: "Ages 7-8",
  //   link: "https://www.amazon.com/Scientific-Explorer-Blowing-Science-Kit/dp/B00B1HXHGQ",
  // },
  // {
  //   id: 616,
  //   title: "Engino STEM Mechanics Kit",
  //   description: "Build working models and learn about gears, pulleys, and mechanical advantage",
  //   image: "/placeholder.svg?height=400&width=300",
  //   category: "stem-activities",
  //   type: "Product",
  //   ageRange: "Ages 9-10",
  //   link: "https://www.amazon.com/ENGINO-Discovering-STEM-Mechanics-Pulleys/dp/B00HNMWFXE",
  // },
  // {
  //   id: 617,
  //   title: "Playz Kaboom! Explosive Combustion Science Kit",
  //   description: "Learn about chemical reactions with safe, explosive experiments",
  //   image: "/placeholder.svg?height=400&width=300",
  //   category: "stem-activities",
  //   type: "Product",
  //   ageRange: "Ages 9-10",
  //   link: "https://www.amazon.com/Playz-Kaboom-Explosive-Combustion-Science/dp/B075RV2ZRR",
  // },
  // {
  //   id: 618,
  //   title: "Elenco Snap Circuits Jr.",
  //   description: "Build over 100 electronic projects with easy snap-together parts",
  //   image: "/placeholder.svg?height=400&width=300",
  //   category: "stem-activities",
  //   type: "Product",
  //   ageRange: "Ages 7-8",
  //   link: "https://www.amazon.com/Snap-Circuits-SC-100-Electronics-Exploration/dp/B00008BFZH",
  // },
  // {
  //   id: 619,
  //   title: "National Geographic Rock Tumbler Kit",
  //   description: "Polish rocks into beautiful gemstones and learn about geology",
  //   image: "/placeholder.svg?height=400&width=300",
  //   category: "stem-activities",
  //   type: "Product",
  //   ageRange: "Ages 9-10",
  //   link: "https://www.amazon.com/National-Geographic-Professional-Rock-Tumbler/dp/B01N0764GK",
  // },
  {
    id: 8,
    title: "Highlights Magazine",
    description: "Classic children's magazine with puzzles, stories, and activities",
    image: "/magazine-cover-highlights.jpg",
    category: "magazines",
    type: "Magazine",
    ageRange: "Ages 5-10",
    link: "https://www.highlights.com/",
  },
  {
    id: 49,
    title: "National Geographic Kids",
    description: "Explore nature, science, and world cultures with stunning photography",
    image: "/magazine-cover-nat-geo-kids.jpg",
    category: "magazines",
    type: "Magazine",
    ageRange: "Ages 7-10",
    link: "https://kids.nationalgeographic.com/",
  },
  {
    id: 50,
    title: "Ranger Rick",
    description: "Wildlife and nature magazine that inspires outdoor exploration",
    image: "/magazine-cover-ranger-rick.jpg",
    category: "magazines",
    type: "Magazine",
    ageRange: "Ages 7-10",
    link: "https://rangerrick.org/",
  },
  {
    id: 51,
    title: "Cricket Magazine",
    description: "Literary magazine featuring stories, poems, and art for young readers",
    image: "/magazine-cover-cricket.jpg",
    category: "magazines",
    type: "Magazine",
    ageRange: "Ages 9-10",
    link: "https://cricketmedia.com/",
  },
  {
    id: 52,
    title: "Goodnight Moon",
    description: "Classic bedtime story that has put generations of babies to sleep by Margaret Wise Brown",
    image: "/goodnight-moon-book-cover-bedtime-story-bunny-room.jpg",
    category: "kids-books",
    type: "Book",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/Goodnight-Moon-Margaret-Wise-Brown/dp/0694003611",
  },
  {
    id: 53,
    title: "Don't Let the Pigeon Drive the Sleigh!",
    description: "Hilarious picture book featuring the persistent pigeon by Mo Willems",
    image: "/don-t-let-the-pigeon-drive-the-sleigh-book-cover-m.jpg",
    category: "kids-books",
    type: "Book",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/Dont-Let-Pigeon-Drive-Sleigh/dp/1423133757",
  },
  {
    id: 54,
    title: "Dragons Love Tacos",
    description: "New York Times bestseller about dragons and their love for tacos by Adam Rubin",
    image: "/dragons-love-tacos-book-cover-colorful-dragon-eati.jpg",
    category: "kids-books",
    type: "Book",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/Dragons-Love-Tacos-Adam-Rubin/dp/0545604265",
  },
  {
    id: 55,
    title: "The Day the Crayons Quit",
    description: "#1 smash hit about crayons on strike by Drew Daywalt and Oliver Jeffers",
    image: "/the-day-the-crayons-quit-book-cover-colorful-crayo.jpg",
    category: "kids-books",
    type: "Book",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/Day-Crayons-Quit-Drew-Daywalt/dp/0399255370",
  },
  {
    id: 56,
    title: "Brown Bear, Brown Bear, What Do You See?",
    description: "Beloved rhythmic picture book with colorful animals by Bill Martin Jr. and Eric Carle",
    image: "/brown-bear-brown-bear-what-do-you-see-book-cover-e.jpg",
    category: "kids-books",
    type: "Book",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/Brown-Bear-What-You-See/dp/0805047905",
  },
  {
    id: 57,
    title: "Chicka Chicka Boom Boom",
    description: "Zany rhyming alphabet book with letters racing up a coconut tree by Bill Martin Jr.",
    image: "/chicka-chicka-boom-boom-book-cover-alphabet-letter.jpg",
    category: "kids-books",
    type: "Book",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/Chicka-Boom-Board-Book/dp/1442450703",
  },
  {
    id: 58,
    title: "Pete the Cat: I Love My White Shoes",
    description: "Popular series about Pete the Cat and his adventures by James Dean",
    image: "/pete-the-cat-i-love-my-white-shoes-book-cover-blue.jpg",
    category: "kids-books",
    type: "Book",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/Pete-Cat-Love-White-Shoes/dp/0061906220",
  },
  {
    id: 59,
    title: "The Giving Tree",
    description: "Classic and perennial favorite about love and giving by Shel Silverstein",
    image: "/the-giving-tree-book-cover-shel-silverstein-tree-b.jpg",
    category: "kids-books",
    type: "Book",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/Giving-Tree-Shel-Silverstein/dp/0060256656",
  },
  {
    id: 60,
    title: "See You Later, Alligator",
    description: "Amazon bestseller about saying goodbye with fun rhymes by Sally Hopgood",
    image: "/see-you-later-alligator-book-cover-cute-alligator-.jpg",
    category: "kids-books",
    type: "Book",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/See-You-Later-Alligator-Sally/dp/1408356597",
  },
  {
    id: 61,
    title: "Little Blue Truck",
    description: "Amazon Editors' top pick about friendship and helping others",
    image: "/little-blue-truck-book-cover-blue-pickup-truck-far.jpg",
    category: "kids-books",
    type: "Book",
    ageRange: "Ages 5-6",
    link: "https://www.amazon.com/Little-Blue-Truck-Alice-Schertle/dp/0544568036",
  },
  {
    id: 62,
    title: "Dog Man",
    description: "Brilliant graphic novel series loved by readers aged 6+ by Dav Pilkey",
    image: "/dog-man-book-cover-dav-pilkey-superhero-dog-comic-.jpg",
    category: "kids-books",
    type: "Book",
    ageRange: "Ages 7-8",
    link: "https://www.amazon.com/Dog-Man-Dav-Pilkey/dp/0545581605",
  },
  {
    id: 63,
    title: "Diary of a Wimpy Kid",
    description: "Bestselling series about middle school life by Jeff Kinney",
    image: "/diary-of-a-wimpy-kid-book-cover-jeff-kinney-stick-.jpg",
    category: "kids-books",
    type: "Book",
    ageRange: "Ages 7-8",
    link: "https://www.amazon.com/Diary-Wimpy-Kid-Book-1/dp/0810993139",
  },
  {
    id: 64,
    title: "Captain Underpants",
    description: "Hilarious series with staying power by Dav Pilkey",
    image: "/captain-underpants-book-cover-dav-pilkey-superhero.jpg",
    category: "kids-books",
    type: "Book",
    ageRange: "Ages 7-8",
    link: "https://www.amazon.com/Adventures-Captain-Underpants-Dav-Pilkey/dp/0590846280",
  },
  {
    id: 65,
    title: "Matilda",
    description: "Classic story about a brilliant girl with magical powers by Roald Dahl",
    image: "/matilda-book-cover-roald-dahl-girl-reading-books.jpg",
    category: "kids-books",
    type: "Book",
    ageRange: "Ages 7-8",
    link: "https://www.amazon.com/Matilda-Roald-Dahl/dp/0142410373",
  },
  {
    id: 66,
    title: "Charlie and the Chocolate Factory",
    description: "Beloved tale of Willy Wonka's magical chocolate factory by Roald Dahl",
    image: "/charlie-and-the-chocolate-factory-book-cover-roald.jpg",
    category: "kids-books",
    type: "Book",
    ageRange: "Ages 7-8",
    link: "https://www.amazon.com/Charlie-Chocolate-Factory-Roald-Dahl/dp/0142410314",
  },
  {
    id: 67,
    title: "Percy Jackson & The Lightning Thief",
    description: "Middle-grade favorite about Greek mythology and adventure by Rick Riordan",
    image: "/percy-jackson-lightning-thief-book-cover.jpg",
    category: "kids-books",
    type: "Book",
    ageRange: "Ages 9-10",
    link: "https://www.amazon.com/Lightning-Thief-Percy-Jackson-Olympians/dp/0786838655",
  },
  {
    id: 68,
    title: "The Giver",
    description: "Thought-provoking dystopian novel by Lois Lowry",
    image: "/the-giver-book-cover-lois-lowry.jpg",
    category: "kids-books",
    type: "Book",
    ageRange: "Ages 9-10",
    link: "https://www.amazon.com/Giver-Lois-Lowry/dp/0544336267",
  },
  {
    id: 69,
    title: "Holes",
    description: "Award-winning adventure about Camp Green Lake by Louis Sachar",
    image: "/holes-book-cover-louis-sachar.jpg",
    category: "kids-books",
    type: "Book",
    ageRange: "Ages 9-10",
    link: "https://www.amazon.com/Holes-Louis-Sachar/dp/0440414806",
  },
  {
    id: 70,
    title: "Artemis Fowl",
    description: "Fantasy adventure about a teenage criminal mastermind by Eoin Colfer",
    image: "/artemis-fowl-book-cover-eoin-colfer.jpg",
    category: "kids-books",
    type: "Book",
    ageRange: "Ages 9-10",
    link: "https://www.amazon.com/Artemis-Fowl-Eoin-Colfer/dp/0786808012",
  },
  {
    id: 71,
    title: "The Undead Fox of Deadwood Forest",
    description: "Amazon Editors' top children's book pick for ages 9-12 in 2025",
    image: "/undead-fox-deadwood-forest-book-cover.jpg",
    category: "kids-books",
    type: "Book",
    ageRange: "Ages 9-10",
    link: "https://www.amazon.com/Undead-Fox-Deadwood-Forest/dp/0593750853",
  },
  {
    id: 72,
    title: "The Book You Wish Your Parents Had Read",
    description: "Insightful guide to understanding yourself and your children better by Philippa Perry",
    image: "/orange-book-cover-the-book-you-wish-your-parents-h.jpg",
    category: "parenting-books",
    type: "Book",
    ageRange: "All Ages",
    link: "https://www.amazon.com/Book-Wish-Your-Parents-Read/dp/0525560572",
  },
  {
    id: 73,
    title: "How to Raise Kids Who Aren't Assholes",
    description: "Science-based strategies for better parenting from tots to teens by Melinda Wenner Moyer",
    image: "/how-to-raise-kids-arent-assholes-melinda-wenner-moyer.jpg",
    category: "parenting-books",
    type: "Book",
    ageRange: "All Ages",
    link: "https://www.amazon.com/Raise-Kids-Arent-Assholes-Parenting/dp/0593086937",
  },
  {
    id: 74,
    title: "Raising Good Humans",
    description: "A mindful guide to breaking the cycle of reactive parenting by Hunter Clarke-Fields",
    image: "/blue-book-cover-raising-good-humans-mindful-parent.jpg",
    category: "parenting-books",
    type: "Book",
    ageRange: "All Ages",
    link: "https://www.amazon.com/Raising-Good-Humans-Breaking-Parenting/dp/1684033888",
  },
  {
    id: 75,
    title: "The Danish Way of Parenting",
    description:
      "What the happiest people in the world know about raising confident children by Jessica Joelle Alexander",
    image: "/blue-book-cover-the-danish-way-of-parenting-happin.jpg",
    category: "parenting-books",
    type: "Book",
    ageRange: "All Ages",
    link: "https://www.amazon.com/Danish-Way-Parenting-Happiest-Confident/dp/014311171X",
  },
  {
    id: 76,
    title: "The Confident Child",
    description: "Raising children to believe in themselves by Terri Apter",
    image: "/yellow-book-cover-the-confident-child-raising-chil.jpg",
    category: "parenting-books",
    type: "Book",
    ageRange: "All Ages",
    link: "https://www.amazon.com/Confident-Child-Raising-Children-Believe/dp/0393328643",
  },
  {
    id: 77,
    title: "You Are Not a Sh*tty Parent",
    description: "How to practice self-compassion and give yourself a break by Carla Naumburg",
    image: "/parenting-book-cover-you-are-not-a-shitty-parent-b.jpg",
    category: "parenting-books",
    type: "Book",
    ageRange: "All Ages",
    link: "https://www.amazon.com/You-Are-Not-Shtty-Parent/dp/1523516895",
  },
  {
    id: 78,
    title: "The Scaffold Effect",
    description: "Raising resilient, self-reliant, and secure kids in an age of anxiety by Harold Koplewicz",
    image: "/white-book-cover-the-scaffold-effect-raising-resil.jpg",
    category: "parenting-books",
    type: "Book",
    ageRange: "All Ages",
    link: "https://www.amazon.com/Scaffold-Parenting-Raising-Resilient-Self-Reliant/dp/0593139364",
  },
  {
    id: 79,
    title: "How to Stop Losing Your Sh*t With Your Kids",
    description: "A practical guide to becoming a calmer, happier parent by Carla Naumburg",
    image: "/yellow-book-cover-how-to-stop-losing-your-shit-wit.jpg",
    category: "parenting-books",
    type: "Book",
    ageRange: "All Ages",
    link: "https://www.amazon.com/How-Stop-Losing-Your-Kids/dp/1523505427",
  },
  {
    id: 80,
    title: "There's No Such Thing as Bad Weather",
    description: "A Scandinavian mom's secrets for raising healthy, resilient kids by Linda Åkeson McGurk",
    image: "/blue-book-cover-there-s-no-such-thing-as-bad-weath.jpg",
    category: "parenting-books",
    type: "Book",
    ageRange: "All Ages",
    link: "https://www.amazon.com/Theres-No-Such-Thing-Weather/dp/1501143697",
  },
  {
    id: 81,
    title: "Remaining You While Raising Them",
    description: "The secret art of confident motherhood by Alli Worthington",
    image: "/colorful-book-cover-remaining-you-while-raising-th.jpg",
    category: "parenting-books",
    type: "Book",
    ageRange: "All Ages",
    link: "https://www.amazon.com/Remaining-You-While-Raising-Them/dp/0310358795",
  },
  {
    id: 82,
    title: "The Parents We Mean to Be",
    description: "How well-intentioned adults undermine children's moral development by Richard Weissbourd",
    image: "/orange-book-cover-the-parents-we-mean-to-be-moral-.jpg",
    category: "parenting-books",
    type: "Book",
    ageRange: "All Ages",
    link: "https://www.amazon.com/Parents-Mean-Well-Intentioned-Undermine-Development/dp/0547248032",
  },
  {
    id: 83,
    title: "Fourteen Talks by Age Fourteen",
    description: "Essential conversations you need to have with your kids before high school by Michelle Icard",
    image: "/pink-book-cover-fourteen-talks-by-age-fourteen-con.jpg",
    category: "parenting-books",
    type: "Book",
    ageRange: "All Ages",
    link: "https://www.amazon.com/Fourteen-Talks-Age-Essential-Conversations/dp/0593137523",
  },
  {
    id: 84,
    title: "The Importance of Being Little",
    description: "What young children really need from grownups by Erika Christakis",
    image: "/white-book-cover-the-importance-of-being-little-ea.jpg",
    category: "parenting-books",
    type: "Book",
    ageRange: "All Ages",
    link: "https://www.amazon.com/Importance-Being-Little-Preschoolers-Grownups/dp/0525429077",
  },
  {
    id: 85,
    title: "When You Wonder, You're Learning",
    description: "Mister Rogers' enduring lessons for raising creative, curious, caring kids by Gregg Behr",
    image: "/beige-book-cover-when-you-wonder-you-re-learning-m.jpg",
    category: "parenting-books",
    type: "Book",
    ageRange: "All Ages",
    link: "https://www.amazon.com/When-You-Wonder-Youre-Learning/dp/0306874733",
  },
  {
    id: 86,
    title: "Life Skills for Kids",
    description: "Equipping your child for the real world by Christine M. Field",
    image: "/purple-book-cover-life-skills-for-kids-practical-p.jpg",
    category: "parenting-books",
    type: "Book",
    ageRange: "All Ages",
    link: "https://www.amazon.com/Life-Skills-Kids-Equipping-Child/dp/0877884722",
  },
  {
    id: 87,
    title: "Raising a Kid Who Can",
    description: "Simple strategies to build a lifetime of adaptability and emotional strength",
    image: "/raising-a-kid-who-can-parenting-book-cover.jpg",
    category: "parenting-books",
    type: "Book",
    ageRange: "All Ages",
    link: "https://www.amazon.com/Raising-Kid-Who-Can-Adaptability/dp/1523518596",
  },
  {
    id: 88,
    title: "Parent Like It Matters",
    description: "How to raise joyful, change-making girls by Janice Johnson Dias",
    image: "/parent-like-it-matters-book-cover-janice-johnson-d.jpg",
    category: "parenting-books",
    type: "Book",
    ageRange: "All Ages",
    link: "https://www.amazon.com/Parent-Like-Matters-Joyful-Change-Making/dp/1984819623",
  },
  {
    id: 89,
    title: "Parenting Right from the Start",
    description: "Laying a healthy foundation in the baby and toddler years by Vanessa Lapointe",
    image: "/parenting-right-from-the-start-book-cover-vanessa-.jpg",
    category: "parenting-books",
    type: "Book",
    ageRange: "All Ages",
    link: "https://www.amazon.com/Parenting-Right-Start-Healthy-Foundation/dp/1966629850",
  },
  {
    id: 90,
    title: "Why Have Kids?",
    description: "A new mom explores the truth about parenting and happiness by Jessica Valenti",
    image: "/why-have-kids-book-cover-jessica-valenti.jpg",
    category: "parenting-books",
    type: "Book",
    ageRange: "All Ages",
    link: "https://www.amazon.com/Why-Have-Kids-Explores-Parenting/dp/0544028066",
  },
  {
    id: 91,
    title: "The 5 Principles of Parenting",
    description: "Your essential guide to raising good humans by Aliza Pressman",
    image: "/5-principles-of-parenting-book-cover-aliza-pressma.jpg",
    category: "parenting-books",
    type: "Book",
    ageRange: "All Ages",
    link: "https://www.amazon.com/Principles-Parenting-Essential-Raising-Humans/dp/1982171359",
  },
  {
    id: 92,
    title: "Muse Magazine",
    description: "STEM magazine for curious kids with cutting-edge science and creative exploration",
    image: "/muse-magazine-cover-science-stem-kids.jpg",
    category: "magazines",
    type: "Magazine",
    ageRange: "Ages 9-10",
    link: "https://cricketmedia.com/childrens-magazines/muse/",
  },
  {
    id: 93,
    title: "Ask Magazine",
    description: "Science and arts magazine answering kids' curious questions about the world",
    image: "/ask-magazine-cover-science-kids-questions.jpg",
    category: "magazines",
    type: "Magazine",
    ageRange: "Ages 7-8",
    link: "https://cricketmedia.com/childrens-magazines/ask/",
  },
  {
    id: 94,
    title: "Chirp Magazine",
    description: "See and do, laugh and learn magazine for preschoolers with stories and activities",
    image: "/chirp-magazine-cover-preschool-kids.jpg",
    category: "magazines",
    type: "Magazine",
    ageRange: "Ages 5-6",
    link: "https://us.owlkids.com/products/chirp-magazine",
  },
  {
    id: 95,
    title: "Ladybug Magazine",
    description: "Literary magazine with captivating read-aloud stories and poems for young children",
    image: "/ladybug-magazine-cover-stories-young-kids.jpg",
    category: "magazines",
    type: "Magazine",
    ageRange: "Ages 5-6",
    link: "https://cricketmedia.com/childrens-magazines/ladybug/",
  },
  {
    id: 96,
    title: "Spider Magazine",
    description: "Literary magazine featuring stories, poems, and activities for early readers",
    image: "/spider-magazine-cover-stories-kids.jpg",
    category: "magazines",
    type: "Magazine",
    ageRange: "Ages 7-8",
    link: "https://cricketmedia.com/childrens-magazines/spider/",
  },
  {
    id: 97,
    title: "ChopChop Magazine",
    description: "Award-winning cooking magazine inspiring families to cook and eat real food together",
    image: "/chopchop-magazine-cover-cooking-kids-family.jpg",
    category: "magazines",
    type: "Magazine",
    ageRange: "All Ages",
    link: "https://www.chopchopfamily.org/",
  },
  {
    id: 98,
    title: "Kazoo Magazine",
    description: "Ad-free magazine for girls featuring strong female role models, stories, and activities",
    image: "/kazoo-magazine-cover-girls-empowerment.jpg",
    category: "magazines",
    type: "Magazine",
    ageRange: "Ages 5-10",
    link: "https://kazoomagazine.com/",
  },
  {
    id: 99,
    title: "Sports Illustrated Kids",
    description: "Sports magazine featuring athletes, games, and activities for young sports fans",
    image: "/sports-illustrated-kids-magazine-cover.jpg",
    category: "magazines",
    type: "Magazine",
    ageRange: "Ages 7-10",
    link: "https://sports-illustrated-kids.magazinesubscriberservices.com/",
  },
  {
    id: 500,
    title: "The Week Junior",
    description: "Current events and news magazine making the world accessible for kids",
    image: "/the-week-junior-magazine-cover-news-kids.jpg",
    category: "magazines",
    type: "Magazine",
    ageRange: "Ages 9-10",
    link: "https://theweekjunior.com/",
  },
  {
    id: 501,
    title: "Okido Magazine",
    description: "Arts and science magazine encouraging creativity and STEM learning through play",
    image: "/okido-magazine-cover-art-science-kids.jpg",
    category: "magazines",
    type: "Magazine",
    ageRange: "Ages 5-6",
    link: "https://store.okido.com/",
  },
  {
    id: 502,
    title: "High Five Magazine",
    description: "Highlights magazine for younger children with puzzles, stories, and activities",
    image: "/high-five-highlights-magazine-cover-preschool.jpg",
    category: "magazines",
    type: "Magazine",
    ageRange: "Ages 5-6",
    link: "https://www.highlights.com/high-five",
  },
  {
    id: 503,
    title: "Ranger Rick Jr.",
    description: "Nature and wildlife magazine for younger children with outdoor adventures",
    image: "/ranger-rick-jr-magazine-cover-nature-wildlife.jpg",
    category: "magazines",
    type: "Magazine",
    ageRange: "Ages 5-6",
    link: "https://rangerrick.org/ranger-rick-jr/",
  },
  {
    id: 504,
    title: "National Geographic Little Kids",
    description: "Science and nature magazine with stunning photos for preschoolers",
    image: "/national-geographic-little-kids-magazine-cover.jpg",
    category: "magazines",
    type: "Magazine",
    ageRange: "Ages 5-6",
    link: "https://www.nationalgeographic.com/subscribe/kids-magazines",
  },
  {
    id: 505,
    title: "Brainspace Magazine",
    description: "Award-winning STEM magazine sparking young imagination and curiosity",
    image: "/brainspace-magazine-cover-stem-kids.jpg",
    category: "magazines",
    type: "Magazine",
    ageRange: "Ages 9-10",
    link: "https://brainspacemagazine.com/",
  },
  {
    id: 506,
    title: "Aquila Magazine",
    description: "Challenging content for curious minds exploring history, science, and culture",
    image: "/aquila-magazine-cover-history-science-kids.jpg",
    category: "magazines",
    type: "Magazine",
    ageRange: "Ages 9-10",
    link: "https://www.aquila.co.uk/",
  },
  {
    id: 507,
    title: "Faces Magazine",
    description: "World cultures and geography magazine exploring diverse peoples and traditions",
    image: "/faces-magazine-cover-world-cultures-kids.jpg",
    category: "magazines",
    type: "Magazine",
    ageRange: "Ages 9-10",
    link: "https://cricketmedia.com/childrens-magazines/faces/",
  },
  {
    id: 508,
    title: "Dig Into History",
    description: "Archaeology and ancient civilizations magazine for young history enthusiasts",
    image: "/dig-into-history-magazine-cover-archaeology-kids.jpg",
    category: "magazines",
    type: "Magazine",
    ageRange: "Ages 9-10",
    link: "https://cricketmedia.com/childrens-magazines/dig/",
  },
  {
    id: 509,
    title: "Cobblestone American History",
    description: "American history magazine bringing the past to life for young readers",
    image: "/cobblestone-american-history-magazine-cover-kids.jpg",
    category: "magazines",
    type: "Magazine",
    ageRange: "Ages 9-10",
    link: "https://cricketmedia.com/childrens-magazines/cobblestone/",
  },
  {
    id: 510,
    title: "Babybug Magazine",
    description: "Board book magazine for babies and toddlers with simple stories and rhymes",
    image: "/babybug-magazine-cover-baby-toddler-stories.jpg",
    category: "magazines",
    type: "Magazine",
    ageRange: "Ages 5-6",
    link: "https://cricketmedia.com/childrens-magazines/babybug/",
  },
  {
    id: 511,
    title: "Click Magazine",
    description: "Science and exploration magazine for young children discovering how things work",
    image: "/click-magazine-cover-science-kids-exploration.jpg",
    category: "magazines",
    type: "Magazine",
    ageRange: "Ages 5-6",
    link: "https://cricketmedia.com/childrens-magazines/click/",
  },
  {
    id: 9,
    title: "KiwiCo",
    description: "Hands-on STEM projects that inspire creativity and learning. $20-30/mo",
    image: "/product-kiwico-crate-box.jpg",
    category: "subscription-boxes",
    type: "Subscription",
    ageRange: "Ages 5-6",
    link: "https://www.kiwico.com/",
  },
  {
    id: 10,
    title: "KiwiCo Tinker Crate",
    description: "Engineering and design projects for older kids. $30-35/mo",
    image: "/product-tinker-crate-box.jpg",
    category: "subscription-boxes",
    type: "Subscription",
    ageRange: "Ages 9-10",
    link: "https://www.kiwico.com/tinker",
  },
  {
    id: 11,
    title: "MEL Science",
    description: "Interactive science experiments with VR experiences. $35-40/mo",
    image: "/product-mel-science-box.jpg",
    category: "subscription-boxes",
    type: "Subscription",
    ageRange: "Ages 7-8",
    link: "https://melscience.com/",
  },
  {
    id: 12,
    title: "Green Kid Crafts",
    description: "Eco-friendly STEM activities and creative projects. $25-30/mo",
    image: "/product-green-kid-crafts-box.jpg",
    category: "subscription-boxes",
    type: "Subscription",
    ageRange: "Ages 5-6",
    link: "https://www.greenkidcrafts.com/",
  },
  {
    id: 13,
    title: "Groovy Lab in a Box",
    description: "STEM experiments with real scientific tools and methods. $30-35/mo",
    image: "/product-groovy-lab-box.jpg",
    category: "subscription-boxes",
    type: "Subscription",
    ageRange: "Ages 7-8",
    link: "https://www.groovylabinbox.com/",
  },
  {
    id: 14,
    title: "Creation Crate",
    description: "Electronics and coding projects for tech-savvy kids. $30-35/mo",
    image: "/product-creation-crate-box.jpg",
    category: "subscription-boxes",
    type: "Subscription",
    ageRange: "Ages 9-10",
    link: "https://www.creationcrate.com/",
  },
  {
    id: 15,
    title: "Literati Kids Book Club",
    description: "Curated children's books delivered monthly. $10-15/mo",
    image: "/product-literati-box.jpg",
    category: "subscription-boxes",
    type: "Subscription",
    ageRange: "Ages 5-6",
    link: "https://literati.com/",
  },
  {
    id: 16,
    title: "OwlCrate Jr",
    description: "Middle-grade book box with exclusive editions and goodies. $35-40/mo",
    image: "/product-owlcrate-jr-box.jpg",
    category: "subscription-boxes",
    type: "Subscription",
    ageRange: "Ages 9-10",
    link: "https://www.owlcrate.com/",
  },
  {
    id: 17,
    title: "Bookroo Picture Books",
    description: "Hand-selected picture books wrapped as gifts. $20-25/mo",
    image: "/product-bookroo-box.jpg",
    category: "subscription-boxes",
    type: "Subscription",
    ageRange: "Ages 5-6",
    link: "https://bookroo.com/",
  },
  {
    id: 18,
    title: "Pages & Co",
    description: "Chapter books and reading activities for young readers. $30-35/mo",
    image: "/product-pages-co-box.jpg",
    category: "subscription-boxes",
    type: "Subscription",
    ageRange: "Ages 7-8",
    link: "https://www.pagesandco.com/",
  },
  {
    id: 19,
    title: "Little Passports World Edition",
    description: "Explore countries and cultures through activities and souvenirs. $18-25/mo",
    image: "/product-little-passports-world-box.jpg",
    category: "subscription-boxes",
    type: "Subscription",
    ageRange: "Ages 7-8",
    link: "https://www.littlepassports.com/",
  },
  {
    id: 20,
    title: "Little Passports USA Edition",
    description: "Discover American states with maps, stickers, and activities. $18-25/mo",
    image: "/product-little-passports-usa-box.jpg",
    category: "subscription-boxes",
    type: "Subscription",
    ageRange: "Ages 7-8",
    link: "https://www.littlepassports.com/",
  },
  {
    id: 21,
    title: "Atlas Crate by KiwiCo",
    description: "Geography and culture projects from around the world. $25-30/mo",
    image: "/product-atlas-crate-box.jpg",
    category: "subscription-boxes",
    type: "Subscription",
    ageRange: "Ages 9-10",
    link: "https://www.kiwico.com/atlas",
  },
  {
    id: 22,
    title: "Universal Yums",
    description: "Snacks from different countries with cultural facts. $15-30/mo",
    image: "/product-universal-yums-box.jpg",
    category: "subscription-boxes",
    type: "Subscription",
    ageRange: "Ages 9-10",
    link: "https://www.universalyums.com/",
  },
  {
    id: 23,
    title: "We Craft Box",
    description: "Creative craft projects with all materials included. $25-30/mo",
    image: "/product-we-craft-box.jpg",
    category: "subscription-boxes",
    type: "Subscription",
    ageRange: "Ages 5-6",
    link: "https://wecraftbox.com/",
  },
  {
    id: 24,
    title: "Doodle Crate by KiwiCo",
    description: "Art and design projects for creative teens. $25-30/mo",
    image: "/product-doodle-crate-box.jpg",
    category: "subscription-boxes",
    type: "Subscription",
    ageRange: "Ages 9-10",
    link: "https://www.kiwico.com/doodle",
  },
  {
    id: 25,
    title: "Pipsticks Sticker Club",
    description: "Curated sticker collections for creative expression. $15-18/mo",
    image: "/product-pipsticks-box.jpg",
    category: "subscription-boxes",
    type: "Subscription",
    ageRange: "Ages 5-6",
    link: "https://www.pipsticks.com/",
  },
  {
    id: 26,
    title: "ArtSnacks",
    description: "Premium art supplies delivered monthly for young artists. $25-30/mo",
    image: "/product-artsnacks-box.jpg",
    category: "subscription-boxes",
    type: "Subscription",
    ageRange: "Ages 7-8",
    link: "https://www.artsnacks.co/",
  },
  {
    id: 27,
    title: "Lovevery Play Kits",
    description: "Developmentally-appropriate toys and activities. $80-120/box",
    image: "/product-lovevery-play-kit-box.jpg",
    category: "subscription-boxes",
    type: "Subscription",
    ageRange: "Ages 5-6",
    link: "https://lovevery.com/",
  },
  {
    id: 28,
    title: "Raddish Kids Cooking Club",
    description: "Cooking projects with recipes and kitchen tools. $25-30/mo",
    image: "/product-raddish-cooking-box.jpg",
    category: "subscription-boxes",
    type: "Subscription",
    ageRange: "Ages 7-8",
    link: "https://www.raddishkids.com/",
  },
  {
    id: 29,
    title: "Bitsbox Coding",
    description: "Learn coding through fun app-building projects. $30-35/mo",
    image: "/product-bitsbox-coding-box.jpg",
    category: "subscription-boxes",
    type: "Subscription",
    ageRange: "Ages 9-10",
    link: "https://bitsbox.com/",
  },
]

export default function ResourcesPage() {
  const [selectedCategory, setSelectedCategory] = useState("all")
  const [selectedAge, setSelectedAge] = useState("All Ages")

  const filteredResources = resources.filter((resource) => {
    const categoryMatch = selectedCategory === "all" || resource.category === selectedCategory
    const ageMatch = selectedAge === "All Ages" || resource.ageRange === selectedAge
    return categoryMatch && ageMatch
  })

  const currentCategoryName = categories.find((cat) => cat.id === selectedCategory)?.name || "All Categories"

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="fixed top-0 left-0 right-0 z-50 w-full px-6 md:px-12 border-b bg-primary-foreground py-6">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <Link href="/">
            <Image src="/plai-logo.png" alt="Plai Logo" width={80} height={40} priority className="w-auto h-16 mx-0" />
          </Link>
        </div>
      </header>

      {/* Main Content */}
      <div className="px-6 md:px-12 py-8 bg-primary-foreground pt-28 md:pt-32">
        <div className="max-w-7xl mx-auto">
          <div className="flex flex-col md:flex-row gap-8">
            {/* Sidebar */}
            <aside className="w-full md:w-64 flex-shrink-0">
              <div className="sticky top-32">
                <h2 className="text-lg font-bold text-primary mb-4">Categories</h2>
                <nav className="space-y-1">
                  {categories.map((category) => {
                    const Icon = category.icon
                    return (
                      <button
                        key={category.id}
                        onClick={() => setSelectedCategory(category.id)}
                        className={`w-full flex items-center gap-3 px-4 py-3 rounded-lg text-left transition-colors ${
                          selectedCategory === category.id
                            ? "bg-secondary text-primary-foreground font-medium"
                            : "text-primary hover:bg-muted/50"
                        }`}
                      >
                        {Icon && <Icon className="w-5 h-5" />}
                        <span>{category.name}</span>
                      </button>
                    )
                  })}
                </nav>
              </div>
            </aside>

            {/* Main Content Area */}
            <main className="flex-1">
              {/* Results Header */}
              <div className="mb-8">
                <p className="text-sm text-muted-foreground mb-6">
                  <span className="font-semibold text-primary">{filteredResources.length}</span> resources found for{" "}
                  <span className="font-semibold">{selectedAge.toLowerCase()}</span> in{" "}
                  <span className="font-semibold">{currentCategoryName.toLowerCase()}</span>
                </p>

                <div className="space-y-2">
                  <h1 className="text-4xl md:text-5xl font-bold text-primary">Explore All Resources</h1>
                  <p className="text-lg text-popover-foreground">
                    {selectedAge !== "All Ages" && `${selectedAge} • `}
                    {selectedCategory !== "all" && `${currentCategoryName} • `}
                    {filteredResources.length} resources to grow together
                  </p>
                </div>

                <div className="mt-6 pt-6 border-t border-border">
                  <h3 className="text-sm font-bold text-primary mb-3">Filter by Age</h3>
                  <div className="flex flex-wrap gap-2">
                    {ageRanges.map((age) => (
                      <Button
                        key={age}
                        variant={selectedAge === age ? "default" : "outline"}
                        size="sm"
                        onClick={() => setSelectedAge(age)}
                        className={
                          selectedAge === age
                            ? "rounded-full bg-secondary text-primary-foreground hover:bg-secondary/90"
                            : "rounded-full"
                        }
                      >
                        {age}
                      </Button>
                    ))}
                  </div>
                </div>
              </div>

              {/* Resource Grid */}
              {filteredResources.length > 0 ? (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                  {filteredResources.map((resource) => (
                    <ResourceCard key={resource.id} resource={resource} />
                  ))}
                </div>
              ) : (
                <div className="text-center py-12">
                  <p className="text-lg text-muted-foreground">No resources found for the selected filters.</p>
                  <Button
                    onClick={() => {
                      setSelectedCategory("all")
                      setSelectedAge("All Ages")
                    }}
                    className="mt-4"
                    variant="outline"
                  >
                    Clear Filters
                  </Button>
                </div>
              )}
            </main>
          </div>
        </div>
      </div>
    </div>
  )
}
